news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
]

newsboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

news/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):

    class Meta():
        model = News
        fields = '__all__'

news/views.py
from django.shortcuts import render, redirect
from .models import News
from .forms import NewsForm

# Create your views here.
def index(request):

    news = News.objects.all()

    context = {
        'news' : news,
    }

    return render(request, 'index.html', context)

def create(request):
    #모든 경우의수
    # - GET : form을 만들어서 html 문서를 사용자에게 리턴 (1~4의 과정)
    # - POST invalid data (검증 실패, 5~9의 과정)
    # - POST valid data (검증 성공, 10~14의 과정)

    # 5, 10. POST 요청
    if request.method == 'POST':
        # 6,11. 사용자 입력 데이터(request.POST)를 담아서 form을 생성
        form = NewsForm(request.POST)
        # 7, 12. 검증 성공, 실패 분기 나눠주기
        if form.is_valid():
            # 13. form을 저장
            form.save()
            # 14. index 페이지로 redirect
            return redirect('news:index')
    # 1. GET 요청
    else:
        # 2. 비어있는 form 생성
        form = NewsForm()
        # 3,8. context dict에 POST 요청
        context = {
            'form' : form,
        }
        # 4,9. create.html을 랜더링
        return render(request, 'form.html', context)

def delete(request, id):
    if request.method == 'POST':
        news = News.objects.get(id=id)
        news.delete()
    return redirect('news:index')

def update(request, id):
    news = News.objects.get(id=id)

    if request.method == 'POST':
        form = NewsForm(request.POST, instance=news)

        if form.is_valid():
            form.save()
            return redirect('news:index')
    else:
        form = NewsForm(instance=news)
    
    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)

    


# def create(request):
#     #(2)
#     if request.method == 'POST':
#         form = NewsForm(request.POST)

#         #(2-1)
#         if form.is_valid():
#             form.save()
#             return redirect('news:index')
#         #(2-2)
#         else:
#             # form = NewsForm(request.POST)
#             context = {
#                 'form' : form,
#             }
#             return render(request, 'create.html', context)


#     #(1)
#     else:
#         form = NewsForm()

#         context = {
#             'form' : form,
#         }
#         return render(request, 'create.html', context)

news/templates/create.html
{% extends 'base.html' %}

{% block body %}
<h2>create</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

news/templates/form.html
{% extends 'base.html' %}

{% block body %}

{% if request.resolver_match.url_name =='create' %}
    <h2>create</h2>
{% else %}
    <h2>update</h2>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

news/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for news in news %}
        <h5>{{news.title}}</h5>
        <p>{{news.content}}</p>
        <p>{{news.created_at}}</p>
        <form action="{% url 'news:delete' id=news.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="delete">
        </form>
        <a href="{% url 'news:update' id=news.id %}">update</a>
        <hr>

    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>여기는 홈그라운드입니다.</h2>
    <a href="{% url 'news:create' %}">기사 생성</a>
    {% block body %}
    {% endblock %}
</body>
</html>